zz3/JavaEE/jpa/src/java/fr/isima/entity/Personne.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.isima.entity;

import java.io.Serializable;
import javax.persistence.*;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author maxime
 */
@Entity
@Table(name = "personne", catalog = "agenda", schema = "")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Personne.findAll", query = "SELECT p FROM Personne p"),
    @NamedQuery(name = "Personne.findByMail", query = "SELECT p FROM Personne p WHERE p.mail = :mail"),
    @NamedQuery(name = "Personne.findByTelephone", query = "SELECT p FROM Personne p WHERE p.telephone = :telephone"),
    @NamedQuery(name = "Personne.findByPrenom", query = "SELECT p FROM Personne p WHERE p.personnePK.prenom = :prenom"),
    @NamedQuery(name = "Personne.findByNom", query = "SELECT p FROM Personne p WHERE p.personnePK.nom = :nom")})
public class Personne implements Serializable {
    private static final long serialVersionUID = 1L;
    @EmbeddedId
    protected PersonnePK personnePK;
    @Size(max = 255)
    @Column(name = "mail", length = 255)
    private String mail;
    @Size(max = 255)
    @Column(name = "telephone", length = 255)
    private String telephone;

    public Personne() {
    }

    public Personne(PersonnePK personnePK) {
        this.personnePK = personnePK;
    }

    public Personne(String prenom, String nom) {
        this.personnePK = new PersonnePK(prenom, nom);
    }

    public PersonnePK getPersonnePK() {
        return personnePK;
    }

    public void setPersonnePK(PersonnePK personnePK) {
        this.personnePK = personnePK;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (personnePK != null ? personnePK.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Personne)) {
            return false;
        }
        Personne other = (Personne) object;
        if ((this.personnePK == null && other.personnePK != null) || (this.personnePK != null && !this.personnePK.equals(other.personnePK))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "fr.isima.entity.Personne[ personnePK=" + personnePK + " ]";
    }
    
}

zz3/JavaEE/jpa/src/java/fr/isima/jsf/PersonneController.java
package fr.isima.jsf;

import fr.isima.entity.Personne;
import fr.isima.jsf.util.JsfUtil;
import fr.isima.jsf.util.PaginationHelper;
import fr.isima.bean.PersonneFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "personneController")
@SessionScoped
public class PersonneController implements Serializable {

    private Personne current;
    private DataModel items = null;
    @EJB
    private fr.isima.bean.PersonneFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public PersonneController() {
    }

    public Personne getSelected() {
        if (current == null) {
            current = new Personne();
            current.setPersonnePK(new fr.isima.entity.PersonnePK());
            selectedItemIndex = -1;
        }
        return current;
    }

    private PersonneFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Personne) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Personne();
        current.setPersonnePK(new fr.isima.entity.PersonnePK());
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PersonneCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Personne) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PersonneUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Personne) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PersonneDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = Personne.class)
    public static class PersonneControllerConverter implements Converter {

        private static final String SEPARATOR = "#";
        private static final String SEPARATOR_ESCAPED = "\\#";

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PersonneController controller = (PersonneController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "personneController");
            return controller.ejbFacade.find(getKey(value));
        }

        fr.isima.entity.PersonnePK getKey(String value) {
            fr.isima.entity.PersonnePK key;
            String values[] = value.split(SEPARATOR_ESCAPED);
            key = new fr.isima.entity.PersonnePK();
            key.setPrenom(values[0]);
            key.setNom(values[1]);
            return key;
        }

        String getStringKey(fr.isima.entity.PersonnePK value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value.getPrenom());
            sb.append(SEPARATOR);
            sb.append(value.getNom());
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Personne) {
                Personne o = (Personne) object;
                return getStringKey(o.getPersonnePK());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + PersonneController.class.getName());
            }
        }
    }
}

zz3/JavaEE/jpa/web/personne/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreatePersonneTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreatePersonneLabel_personnePK_nom}" for="personnePK_nom" />
                    <h:inputText id="personnePK_nom" value="#{personneController.selected.personnePK.nom}" title="#{bundle.CreatePersonneTitle_personnePK_nom}" required="true" requiredMessage="#{bundle.CreatePersonneRequiredMessage_personnePK_nom}"/>
                    <h:outputLabel value="#{bundle.CreatePersonneLabel_personnePK_prenom}" for="personnePK_prenom" />
                    <h:inputText id="personnePK_prenom" value="#{personneController.selected.personnePK.prenom}" title="#{bundle.CreatePersonneTitle_personnePK_prenom}" required="true" requiredMessage="#{bundle.CreatePersonneRequiredMessage_personnePK_prenom}"/>
                    <h:outputLabel value="#{bundle.CreatePersonneLabel_mail}" for="mail" />
                    <h:inputText id="mail" value="#{personneController.selected.mail}" title="#{bundle.CreatePersonneTitle_mail}" />
                    <h:outputLabel value="#{bundle.CreatePersonneLabel_telephone}" for="telephone" />
                    <h:inputText id="telephone" value="#{personneController.selected.telephone}" title="#{bundle.CreatePersonneTitle_telephone}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{personneController.create}" value="#{bundle.CreatePersonneSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{personneController.prepareList}" value="#{bundle.CreatePersonneShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.CreatePersonneIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

zz3/JavaEE/jpa/web/personne/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditPersonneTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditPersonneLabel_personnePK_nom}" for="personnePK_nom" />
                    <h:inputText id="personnePK_nom" value="#{personneController.selected.personnePK.nom}" title="#{bundle.EditPersonneTitle_personnePK_nom}" required="true" requiredMessage="#{bundle.EditPersonneRequiredMessage_personnePK_nom}"/>
                    <h:outputLabel value="#{bundle.EditPersonneLabel_personnePK_prenom}" for="personnePK_prenom" />
                    <h:inputText id="personnePK_prenom" value="#{personneController.selected.personnePK.prenom}" title="#{bundle.EditPersonneTitle_personnePK_prenom}" required="true" requiredMessage="#{bundle.EditPersonneRequiredMessage_personnePK_prenom}"/>
                    <h:outputLabel value="#{bundle.EditPersonneLabel_mail}" for="mail" />
                    <h:inputText id="mail" value="#{personneController.selected.mail}" title="#{bundle.EditPersonneTitle_mail}" />
                    <h:outputLabel value="#{bundle.EditPersonneLabel_telephone}" for="telephone" />
                    <h:inputText id="telephone" value="#{personneController.selected.telephone}" title="#{bundle.EditPersonneTitle_telephone}" />
                </h:panelGrid>
                <h:commandLink action="#{personneController.update}" value="#{bundle.EditPersonneSaveLink}"/>
                <br />
                <br />
                <h:commandLink action="View" value="#{bundle.EditPersonneViewLink}" immediate="true"/>
                <br />
                <h:commandLink action="#{personneController.prepareList}" value="#{bundle.EditPersonneShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.EditPersonneIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

zz3/JavaEE/jpa/web/personne/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListPersonneTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListPersonneEmpty}" rendered="#{personneController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{personneController.items.rowCount > 0}">
                    <h:outputText value="#{personneController.pagination.pageFirstItem + 1}..#{personneController.pagination.pageLastItem + 1}/#{personneController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{personneController.previous}" value="#{bundle.Previous} #{personneController.pagination.pageSize}" rendered="#{personneController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{personneController.next}" value="#{bundle.Next} #{personneController.pagination.pageSize}" rendered="#{personneController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{personneController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonneTitle_personnePK_nom}"/>
                            </f:facet>
                            <h:outputText value="#{item.personnePK.nom}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonneTitle_personnePK_prenom}"/>
                            </f:facet>
                            <h:outputText value="#{item.personnePK.prenom}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonneTitle_mail}"/>
                            </f:facet>
                            <h:outputText value="#{item.mail}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonneTitle_telephone}"/>
                            </f:facet>
                            <h:outputText value="#{item.telephone}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{personneController.prepareView}" value="#{bundle.ListPersonneViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{personneController.prepareEdit}" value="#{bundle.ListPersonneEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{personneController.destroy}" value="#{bundle.ListPersonneDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{personneController.prepareCreate}" value="#{bundle.ListPersonneCreateLink}"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.ListPersonneIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

zz3/JavaEE/jpa/web/personne/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewPersonneTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewPersonneLabel_personnePK_nom}"/>
                    <h:outputText value="#{personneController.selected.personnePK.nom}" title="#{bundle.ViewPersonneTitle_personnePK_nom}"/>
                    <h:outputText value="#{bundle.ViewPersonneLabel_personnePK_prenom}"/>
                    <h:outputText value="#{personneController.selected.personnePK.prenom}" title="#{bundle.ViewPersonneTitle_personnePK_prenom}"/>
                    <h:outputText value="#{bundle.ViewPersonneLabel_mail}"/>
                    <h:outputText value="#{personneController.selected.mail}" title="#{bundle.ViewPersonneTitle_mail}"/>
                    <h:outputText value="#{bundle.ViewPersonneLabel_telephone}"/>
                    <h:outputText value="#{personneController.selected.telephone}" title="#{bundle.ViewPersonneTitle_telephone}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{personneController.destroyAndView}" value="#{bundle.ViewPersonneDestroyLink}"/>
                <br />
                <br />
                <h:commandLink action="Edit" value="#{bundle.ViewPersonneEditLink}"/>
                <br />
                <h:commandLink action="#{personneController.prepareCreate}" value="#{bundle.ViewPersonneCreateLink}" />
                <br />
                <h:commandLink action="#{personneController.prepareList}" value="#{bundle.ViewPersonneShowAllLink}"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.ViewPersonneIndexLink}" action="/index" immediate="true" />

            </h:form>
        </ui:define>
    </ui:composition>

</html>